---
- name: Start and maintain database
  hosts: localhost
  tasks:
  # create a new migration from database "subscriptions"
  - name: Create a migration
    ansible.builtin.shell: |
      timestamp=$(date +"%Y%m%d%H%M%S")
      backup_filename="V${timestamp}__backup_data.sql"
      mysqldump -u root -padmin8960392 subscriptions -h 127.0.0.1 > "migrations/$backup_filename"
      echo "Created migration: $backup_filename"
    register: flyway_backup
    changed_when: flyway_backup.rc == 0

  - name: stop mysql
    ansible.builtin.shell: sudo service mysql stop > /tmp/mysqldown.txt
    args:
      creates: /tmp/mysqldown.txt
  
  # clear log
  - name: Remove mysql.txt file (delete file)
    ansible.builtin.file:
      path: /tmp/mysql.txt
      state: absent

